services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - WEBUI_PORT=6060
    ports:      
      - 6060:6060
      - 6881:6881
      - 6881:6881/udp
    volumes:
      #- qbittorrent:/config
      - /mnt/downloads:/downloads
      - /mnt/downloadsp:downloadsp
    networks:
      - docker
    restart: unless-stopped
volumes:
  qbittorrent:
    name: qbittorrent
networks:
  docker:
    name: docker
