services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      #- BASE_URL=/ombi #optional
    volumes:
      #- /path/to/appdata/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
