services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    ports:
      - 80:80
      - 443:443
    networks:
      - docker
    restart: unless-stopped
networks:
  docker:
    name: docker
